site_name: YS's note
site_url: https://www.yusaito.com/mynote/
site_author: Yu Saito

theme:
  favicon: "favicon.ico"
  custom_dir: "theme"
  language: en
  name: material
  palette:
    accent: Indigo
    primary: Indigo
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yseeker

extra_css:
  - https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang:
        - en
  - awesome-pages
  - macros
  - mdoctag:
      tagpage_dir: "tags"
      data_filename: "tags.json"

markdown_extensions:
  - hbfm.quote_uri_hash
  - hbfm.inline_coloring
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - markdown.extensions.nl2br
  - fontawesome_markdown
  - def_list
  - admonition
  - meta
  - footnotes
  - pymdownx.critic
  - markdown_blockdiag:
      format: svg
  - toc:
      permalink: "¶"
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.highlight:
      linenums: true

# Page tree
nav:
  - Home: albumentations.md
  - Utils:
      - Linux: linux_command.md
      - Git: git.md
      - Docker: docker.md
      - Google Colab: colab.md
      - LabRAD: labrad.md
  - Python:
      - Basics: python_basis.md
      - AL-DS: index.md
  - ML:
      - albumentations: albumentations.md
      - pytorch templates: pytorch_basis.md
      - Gereative models:
          - GAN basis: gan.md
          - other: dcgan.md
